#!/bin/bash

# nix setup
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install)

# nix-darwin setup
sudo mkdir -p /etc/nix-darwin
cd /etc/nix-darwin
nix --extra-experimental-features nix-command --extra-experimental-features flakes flake init -t nix-darwin/master
sed -i '' "s/simple/$(scutil --get LocalHostName)/" flake.nix
sudo mv /etc/bashrc /etc/bashrc.before-nix-darwin
sudo mv /etc/zshrc /etc/zshrc.before-nix-darwi
sudo nix --extra-experimental-features nix-command --extra-experimental-features flakes run nix-darwin/master#darwin-rebuild -- switch

# build host configuration
sudo darwin-rebuild switch --flake /Users/lucas/System#$host
